- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - release-notes-jobs-python3
      - publish-openstack-docs-pti
      - check-requirements
    check:
      jobs:
        - openstack-tox-lower-constraints
        - openstack-tox-cover:
            voting: false
    gate:
      queue: kuryr
      jobs:
        - openstack-tox-lower-constraints
